DIR_EXECUTABLE = "./executable"
DIR_UTILS = "./utils"
DIR_LOG = "./.log"
DIR_DATASETS = "./datasets"
DIR_DATASETS_CONFIG = "./datasets/config"
DIR_DATASETS_BUILD  = "./datasets/build"
POS_LABEL = "disturbed"
NEG_LABEL = "normal"